on:
  push:
    branches:
      - feat/auto-label-conflicts
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: JeremyDec/auto-label-merge-conflicts@new
        with:
          CONFLICT_LABEL_NAME: 'has conflicts'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
